server:
#  端口设置8080
  port: 8080

spring:
  application:
    name: Novi
  datasource:
    url: jdbc:mysql://49.235.238.143:3306/novi?useUnicode=true&characterEncoding=UTF-8
    username: Novi-Admin
    password: Novi-Admin-PassWord!
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名的开关
    map-underscore-to-camel-case: true

#配置JWT
novi:
  jwt:
    # 秘钥
    secret-key: "novi-project-by-n1etzsch3-test-secret-key"
    # Token 有效期 (毫秒), 这里设置为 1 天
    ttl: 86400000
    # Token 在 Header 中的名称
    header-name: "Authorization"

# 分页插件配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

# 配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG


# 配置云对象存储服务
#tencent:
#    cos: