server:
#  端口设置8080
  port: 8080

spring:
  application:
    name: Novi
  datasource:
    # 1. 使用环境变量设置完整的 URL
    url: ${SPRING_DATASOURCE_URL}

    # 2. 使用环境变量设置用户名
    username: ${SPRING_DATASOURCE_USERNAME}

    # 3. 使用环境变量设置密码
    password: ${SPRING_DATASOURCE_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      # 4. 使用环境变量设置 API Key
      api-key: ${SPARK_API_KEY}

      base-url: https://spark-api-open.xf-yun.com/v1
      chat:
        options:
          model: max-32k
        completions-path: /chat/completions


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名的开关
    map-underscore-to-camel-case: true

#配置JWT
novi:
  jwt:
    # 秘钥
    secret-key: "novi-project-by-n1etzsch3-test-secret-key"
    # Token 有效期 (毫秒), 这里设置为 1 天
    ttl: 86400000
    # Token 在 Header 中的名称
    header-name: "Authorization"

# 分页插件配置
#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

# 配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: DEBUG
    # 开启 Spring AI 核心日志
    org.springframework.ai: TRACE

    # 开启 Spring 默认 HTTP 客户端 (WebClient) 的详细日志
    # 这将打印出完整的请求和响应内容，包括 URL、Headers 和 Body
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE


# 配置云对象存储服务
#tencent:
#    cos: